sudo: required

services:
  - docker

env:
  global:
    - CONTAINER_VERSION=1.11.10-20

notifications:
  email: false

branches:
  only:
    - master

install:
  - sudo apt-get update && sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull stono/docker-nginx-letsencrypt
  - docker build -f Dockerfile -t stono/docker-nginx-letsencrypt:latest --cache-from stono/docker-nginx-letsencrypt .
  - docker tag stono/docker-nginx-letsencrypt:latest stono/docker-nginx-letsencrypt:$CONTAINER_VERSION

script:
  - docker images | grep docker-nginx-letsencrypt | grep -q $CONTAINER_VERSION

after_success:
  - docker push stono/docker-nginx-letsencrypt
  - docker push stono/docker-nginx-letsencrypt:$CONTAINER_VERSION
