version: '2'

services:
  nginx:
    image: stono/docker-nginx-letsencrypt 
    restart: always
    environment:
      - HOST_KARLSTONEY=karlstoney.com,localhost:9000,default_server
      - HOST_WWWKARLSTONEY=www.karlstoney.com,karlstoney.com,redirect
    ports:
      - 443:443
      - 80:80
