version: '2'

services:
  nginx:
    image: stono/docker-nginx-letsencrypt 
    restart: always
    volumes:
      - ./config.json:/config/config.json
    environment:
      - LETSENCRYPT=true
      - LETSENCRYPT_EMAIL=test@test.com
    ports:
      - 443:443
      - 80:80
