version: '2'

services:
  nginx:
    image: stono/docker-nginx-letsencrypt 
    restart: always
    environment:
      - HOST_GATEWAY=karlstoney.com,localhost:9000,default_server
    ports:
      - 443
      - 80
