version: '2'

services:
  nginx:
    image: stono/docker-nginx-letsencrypt 
    restart: always
    volumes:
      - ./config.js:/config/config.js
    environment:
      - LETSENCRYPT=true
      - LETSENCRYPT_EMAIL=test@test.com
      - DOMAIN_SUFFIX=preprod.
    ports:
      - 443:443
      - 80:80
